content/en/release-notes.html, content/en/release-notes.md, content/pt/release-notes.html, content/pt/release-notes.md, layouts/shortcodes/iframe.html
Adding release notes for v1.5 version english and pt. 
It is in draft because the images are still broken on aws
=> feat: Adds release notes

content/en/release-notes.md, content/pt/release-notes.md
=> :bug: Fixes url for release-notes.md

content/en/resources/customization/beagle-for-android/proguard-configuration.md, content/pt/resources/customization/beagle-for-android/proguard-configuration.md
with new commits into in master of the beagle, you don't need more add some configuration in your ProGuard I update the documentation with the new way to configure your application
=> refactor: update proguard documentation

content/en/resources/customization/beagle-for-android/proguard-configuration.md, content/pt/resources/customization/beagle-for-android/proguard-configuration.md
=> Revert "refactor: update proguard documentation"

content/en/api/accessibility.md, content/en/api/components/forms/simple-form.md, content/en/api/components/layout/listview.md, content/en/api/components/layout/pageview.md, content/en/api/components/lazy.md, content/en/api/components/ui/button.md, content/en/api/components/ui/image/imagepath.md, content/en/api/components/ui/webview.md, content/pt/api/accessibility.md, content/pt/api/components/forms/simple-form.md, content/pt/api/components/layout/listview.md, content/pt/api/components/layout/pageview.md, content/pt/api/components/lazy.md, content/pt/api/components/ui/button.md, content/pt/api/components/ui/image/imagepath.md, content/pt/api/components/ui/webview.md
It fix the kotlin DSL examples on the API components.
=> fixing the kotlin dsl examples on the api components

content/en/api/accessibility.md, content/pt/api/accessibility.md
**Beagle version 1.6.0**
This PR adds to the documentation a new property (isHeader) available in Accessibility.
=> feat: adding accessibilityHeader to doc

content/en/api/components/forms/simple-form.md, content/en/api/components/ui/textinput.md, content/pt/api/components/forms/simple-form.md, content/pt/api/components/ui/textinput.md
**Beagle version 1.6.0**
This PR updates the documentation, adding new validation attributes for simple form and text input.
=> feat: updates simple form and text input 

content/en/resources/customization/beagle-for-ios/beagle-view.md, content/pt/resources/customization/beagle-for-ios/beagle-view.md
**Beagle version 1.6.0**
This PR adds the documentation to using states in iOS's BeagleView, it provides the user a way to configure BeagleView's state, it is something that we didn't have in iOS before.
=> feat: adding BeagleView states to iOS doc

content/en/get-started/installing-beagle/ios.md, content/en/get-started/using-beagle/ios.md, content/en/resources/components/components-with-context.md, content/pt/get-started/installing-beagle/ios.md, content/pt/get-started/using-beagle/ios.md, content/pt/resources/components/components-with-context.md
Documentation changes in conformance with https://github.com/ZupIT/beagle/pull/1118
=> feat: iOS - Remove BeagleSchema module

content/en/resources/customization/beagle-for-android/proguard-configuration.md, content/pt/resources/customization/beagle-for-android/proguard-configuration.md
=> Revert "Revert "refactor: update proguard documentation""

content/en/api/components/ui/button.md, content/pt/api/components/ui/button.md
Adding atribute enabled in button
=> fix: Adding atribute enabled in button

content/en/api/components/ui/textinput.md, content/pt/api/components/ui/textinput.md
fix: deprecated atribute hidden.
=> fix: deprecated atribute hidden

content/en/api/components/layout/listview.md, content/pt/api/components/layout/listview.md
Adding attribute isScrollIndicatorVisible.
=> add: attribute isScrollIndicatorVisible

content/en/resources/customization/beagle-for-ios/custom-beagle-navigation-controller.md, content/pt/resources/customization/beagle-for-ios/custom-beagle-navigation-controller.md
**Beagle version 1.6.0**
This PR adds the documentation on how to use default error view on iOS
=> feat: adding default error view on iOS

content/en/get-started/using-beagle/android.md, content/pt/get-started/using-beagle/android.md
Fixes the image link on Using beagle Android Step 3 (main)
=> Fix image on Step 3 Using beagle Android

content/en/api/components/layout/pageview.md, content/pt/api/components/layout/pageview.md
fixes the pageView example on API components layout
fixes the reported issue from user ZupIT/beagle#1447
=> fixes the pageView example on API components layout v1.6

content/en/api/components/layout/pageview.md, content/pt/api/components/layout/pageview.md
fixes the pageView example on API components layout
fixes the reported issue from user ZupIT/beagle#1447
=> fixes the pageView example on API components layout V1.5

content/en/api/components/layout/pageview.md, content/pt/api/components/layout/pageview.md
fixes the pageView example on API components layout
fixes the reported issue from user https://github.com/ZupIT/beagle/issues/1447
=> fixes the pageView example on API components layout

content/en/api/components/layout/pageview.md, content/en/resources/live-preview.md, content/pt/resources/live-preview.md
=> Fix shield live preview v1.5

content/en/resources/live-preview.md, content/pt/resources/live-preview.md
fixes version shield in live-preview page main
=> fixes version shield in live-preview page main

content/en/resources/live-preview.md, content/pt/resources/live-preview.md
fixes version shield in live-preview page
=> fixes version shield in live-preview page v1.6

.gitignore, content/en/get-started/installing-beagle/android.md, content/en/get-started/installing-beagle/backend.md, content/en/get-started/using-beagle-helpers/android/beagle-defaults.md, content/en/get-started/using-beagle-helpers/android/beagle-scaffold.md, content/en/get-started/using-beagle/android.md, content/en/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md, content/en/tutorials/how-to-create-new-actions.md, content/pt/get-started/installing-beagle/android.md, content/pt/get-started/installing-beagle/backend.md, content/pt/get-started/using-beagle-helpers/Android/beagle-defaults.md, content/pt/get-started/using-beagle-helpers/Android/beagle-scaffold.md, content/pt/get-started/using-beagle/android.md, content/pt/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md, content/pt/tutorials/how-to-create-new-actions.md
Fixes #451 
This PR adds documentation to `gradle` configuration in backend starter session, fixes typos, library description in code snippet and `.gitignore`.
=> Improved sentences and fixed some erros v1.6

.gitignore, content/en/get-started/installing-beagle/android.md, content/en/get-started/installing-beagle/backend.md, content/en/get-started/using-beagle-helpers/android/beagle-defaults.md, content/en/get-started/using-beagle-helpers/android/beagle-scaffold.md, content/en/get-started/using-beagle/android.md, content/en/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md, content/en/tutorials/how-to-create-new-actions.md, content/pt/get-started/installing-beagle/android.md, content/pt/get-started/installing-beagle/backend.md, content/pt/get-started/using-beagle-helpers/Android/beagle-defaults.md, content/pt/get-started/using-beagle-helpers/Android/beagle-scaffold.md, content/pt/get-started/using-beagle/android.md, content/pt/resources/customization/beagle-for-android/custom-widget/serverdrivencomponent-custom-widget.md, content/pt/tutorials/how-to-create-new-actions.md
Fixes #451 
This PR adds documentation to `gradle` configuration in backend starter session, fixes typos, library description in code snippet and `.gitignore`.
=> Improved sentences and fixed some erros main

content/en/api/actions/sendrequest.md, content/pt/api/actions/sendrequest.md
updates the api send-request example
=> updates the api send-request example

content/en/api/components/layout/container.md, content/en/resources/style/ios.md, content/pt/api/components/layout/container.md, content/pt/resources/style/ios.md
**Beagle version 1.7.0**
This PR adds the documentation to styleId in Container and updates the style's iOS page, adding an example for Container and fixing some examples on other components styles.
=> feat: adding styleId doc on container

content/en/resources/customization/beagle-for-android/network-client.md, content/pt/resources/customization/beagle-for-android/network-client.md
Adds HttpClientFactory explanation.
=> chore: Update Android network client doc

content/en/get-started/installing-beagle/ios.md, content/pt/get-started/installing-beagle/ios.md
https://github.com/ZupIT/beagle/pull/1484
Add SwiftPM support section in installing Beagle iOS doc
=> feat: iOS - Add SwiftPM support section in installing Beagle iOS

content/en/api/actions/navigate/route/remote.md, content/pt/api/actions/navigate/route/remote.md
**Beagle version 1.7.0**
This PR adds the documentation to httpAdditionalData property added on Navigate.Remote.
=> feat: adding additional data on remote

content/en/get-started/installing-beagle/ios.md, content/pt/get-started/installing-beagle/ios.md
https://github.com/ZupIT/beagle/pull/1511
Update Yoga version and remove YogaKit requirements from pod get started
=> docs: iOS - Update Yoga version

layouts/shortcodes/playground.html
Add cross project, allowing the playground to display examples of different versions.
Closes https://github.com/ZupIT/beagle-playground/issues/137
=> add cross-project

content/en/api/components/layout/pageview.md, content/en/get-started/installing-beagle/backend.md, content/pt/get-started/installing-beagle/backend.md
fix image link micronaut in get started backend
=> Fix/image link get started backend v1.5

content/en/api/components/layout/pageview.md, content/en/get-started/installing-beagle/backend.md, content/pt/get-started/installing-beagle/backend.md
fixes the shields in get started backed
=> Fix shields backend get started v1.5

content/en/api/accessibility.md, content/en/api/components/layout/_index.md, content/en/api/components/layout/accessibility.md, content/en/api/components/layout/center.md, content/en/api/components/layout/column.md, content/en/api/components/layout/container.md, content/en/api/components/layout/expanded.md, content/en/api/components/layout/margin.md, content/en/api/components/layout/overview.md, content/en/api/components/layout/padding.md, content/en/api/components/layout/row.md, content/en/api/components/layout/sizedbox.md, content/en/api/components/layout/styled.md, content/pt/api/accessibility.md, content/pt/api/components/layout/SizedBox.md, content/pt/api/components/layout/_index.md, content/pt/api/components/layout/accessibility.md, content/pt/api/components/layout/center.md, content/pt/api/components/layout/column.md, content/pt/api/components/layout/container.md, content/pt/api/components/layout/expanded.md, content/pt/api/components/layout/margin.md, content/pt/api/components/layout/overview.md, content/pt/api/components/layout/padding.md, content/pt/api/components/layout/row.md, content/pt/api/components/layout/scrollview.md, content/pt/api/components/layout/styled.md, yarn.lock
New functions created:
Column -> Only application of column type flex
Row -> Only application of row type flex
Accessibility -> Helper to facilitate adding accessibility to a component
Center -> Helper to help centralize the component
Expanded -> Helper to help the component occupy the available space.
Margin -> Helper to help the margin apply to the component.
Padding -> Helper to help padding the component.
SizedBox -> Helper to help define a component size.
Styled -> Simplifies the application of styling and is a way to make the compose more robust.
If you want to know more about theses documentation check this PR in the beagle: https://github.com/ZupIT/beagle/pull/1457
=> docs: add new Layout Functions: Center, Column and Row..

content/en/api/accessibility.md, content/en/api/components/layout/_index.md, content/en/api/components/layout/accessibility.md, content/en/api/components/layout/center.md, content/en/api/components/layout/column.md, content/en/api/components/layout/container.md, content/en/api/components/layout/expanded.md, content/en/api/components/layout/margin.md, content/en/api/components/layout/overview.md, content/en/api/components/layout/padding.md, content/en/api/components/layout/row.md, content/en/api/components/layout/sizedbox.md, content/en/api/components/layout/styled.md, content/pt/api/accessibility.md, content/pt/api/components/layout/SizedBox.md, content/pt/api/components/layout/_index.md, content/pt/api/components/layout/accessibility.md, content/pt/api/components/layout/center.md, content/pt/api/components/layout/column.md, content/pt/api/components/layout/expanded.md, content/pt/api/components/layout/margin.md, content/pt/api/components/layout/overview.md, content/pt/api/components/layout/padding.md, content/pt/api/components/layout/row.md, content/pt/api/components/layout/scrollview.md, content/pt/api/components/layout/styled.md, yarn.lock
adjust the main to follow release 1.7
=> docs: add new Layout Functions: Center, Column and Row.. (#516)

content/en/get-started/using-beagle-helpers/ios/beagle-scaffold.md, content/pt/get-started/using-beagle-helpers/iOS/beagle-scaffold.md
removing unnecessary step from beagle scaffold iOS
=> update: removing unnecessary step v.1.7

content/pt/get-started/using-beagle-helpers/iOS/beagle-scaffold.md
Removing unnecessary step from Beagle Scaffold iOS pt
=> Update beagle-scaffold.md PT

content/en/get-started/using-beagle-helpers/ios/beagle-scaffold.md
Removing a step not necessary at Beagle Scaffold config for iOS
=> Update beagle-scaffold.md EN

content/en/get-started/creating-a-project-from-scratch/case-backend.md, content/en/get-started/using-beagle/backend.md, content/pt/get-started/creating-a-project-from-scratch/case-backend.md, content/pt/get-started/using-beagle/backend.md
adjusting backend example that shows where to create the service, controller and builder classes
=> adjusting backend example that shows where to create the service package

content/en/api/global-context.md, content/pt/api/global-context.md
Fix GlobalContext iOS samples.
=> fix: GlobalContext iOS code samples

content/en/get-started/creating-a-project-from-scratch/case-android/design-system-with-beagle-android.md, content/en/get-started/creating-a-project-from-scratch/case-backend.md, content/en/get-started/creating-a-project-from-scratch/case-ios/defining-styles-on-beagle-ios.md, content/en/get-started/creating-a-project-from-scratch/case-web.md, content/pt/get-started/creating-a-project-from-scratch/case-android/design-system-with-beagle-android.md, content/pt/get-started/creating-a-project-from-scratch/case-backend.md, content/pt/get-started/creating-a-project-from-scratch/case-ios/defining-styles-on-beagle-ios.md, content/pt/get-started/creating-a-project-from-scratch/case-web.md
Update of the beagle code examples using applyStyle and applyFlex to use the new setFlex and setStyle implementation
=> update: example of applyStyle and applyFlex on the get started pages

content/en/api/components/layout/listview.md, content/en/api/components/ui/tabview.md, content/en/api/context/operations/arrays-manipulation-operator.md, content/en/api/context/operations/comparison-operator.md, content/en/api/context/operations/logic-operator.md, content/en/api/context/operations/other-operators.md, content/en/api/context/operations/string-manipulation-operator.md, content/en/api/widget.md, content/pt/api/components/layout/listview.md, content/pt/api/components/ui/tabview.md, content/pt/api/context/operations/arrays-manipulation-operator.md, content/pt/api/context/operations/comparison-operator.md, content/pt/api/context/operations/logic-operator.md, content/pt/api/context/operations/other-operators.md, content/pt/api/context/operations/string-manipulation-operator.md, content/pt/api/widget.md
Update of the beagle code examples using applyStyle and applyFlex to use the new setFlex and setStyle implementation.
=> update: example of applyStyle and applyFlex on the api pages on branch main

content/en/api/components/layout/listview.md, content/en/api/components/ui/tabview.md, content/en/api/context/operations/arrays-manipulation-operator.md, content/en/api/context/operations/comparison-operator.md, content/en/api/context/operations/logic-operator.md, content/en/api/context/operations/other-operators.md, content/en/api/context/operations/string-manipulation-operator.md, content/en/api/widget.md, content/pt/api/components/layout/listview.md, content/pt/api/components/ui/tabview.md, content/pt/api/context/operations/arrays-manipulation-operator.md, content/pt/api/context/operations/comparison-operator.md, content/pt/api/context/operations/logic-operator.md, content/pt/api/context/operations/other-operators.md, content/pt/api/context/operations/string-manipulation-operator.md, content/pt/api/widget.md
Update of the beagle code examples using applyStyle and applyFlex to use the new setFlex and setStyle implementation.
=> update: example of applyStyle and applyFlex on the api pages

content/en/api/context/operations/string-manipulation-operator.md, content/pt/api/context/operations/string-manipulation-operator.md
Change in lowercase operation example from lowecase to lowercase.
=> refactor: change in the lowercase operation example in main

content/en/api/context/operations/string-manipulation-operator.md, content/pt/api/context/operations/string-manipulation-operator.md
Change in lowercase operation example from lowecase to lowercase.
=> refactor: change in the lowercase operation example in v1.7

content/en/api/context/operations/string-manipulation-operator.md, content/pt/api/context/operations/string-manipulation-operator.md
Change in lowercase operation example from lowecase to lowercase.
=> refactor: change in the lowercase operation example in v1.6

content/en/api/context/operations/string-manipulation-operator.md, content/pt/api/context/operations/string-manipulation-operator.md
Change in lowercase operation example from lowecase to lowercase.
=> refactor: change in the lowercase operation example in  v1.5

content/en/get-started/installing-beagle/backend.md, content/en/get-started/installing-beagle/react-native.md, content/en/get-started/using-beagle/backend.md, content/en/get-started/using-beagle/react-native.md, content/en/overview.md, content/en/resources/customization/beagle-for-backend/_index.md, content/en/resources/customization/beagle-for-backend/beagle-framework.md, content/en/resources/customization/beagle-for-backend/serialization.md, content/en/resources/customization/beagle-for-react-native/_index.md, content/en/resources/customization/beagle-for-react-native/cache.md, content/en/resources/customization/beagle-for-react-native/development.md, content/en/resources/customization/beagle-for-react-native/local-images.md, content/en/resources/customization/beagle-for-react-native/localhost.md, content/en/resources/customization/beagle-for-react-native/web-view.md, content/pt/get-started/installing-beagle/backend.md, content/pt/get-started/installing-beagle/react-native.md, content/pt/get-started/using-beagle/backend.md, content/pt/get-started/using-beagle/react-native.md, content/pt/overview.md, content/pt/resources/customization/beagle-for-backend/_index.md, content/pt/resources/customization/beagle-for-backend/beagle-framework.md, content/pt/resources/customization/beagle-for-backend/serialization.md, content/pt/resources/customization/beagle-for-react-native/_index.md, content/pt/resources/customization/beagle-for-react-native/cache.md, content/pt/resources/customization/beagle-for-react-native/development.md, content/pt/resources/customization/beagle-for-react-native/local-images.md, content/pt/resources/customization/beagle-for-react-native/localhost.md, content/pt/resources/customization/beagle-for-react-native/web-view.md
Adds documentation for Beagle React Native Beta
- Added the Beagle React Native version badge to the overview.
- Created the section Getting started > Installing Beagle > React Native.
- Created the section Getting started > Using Beagle > React Native.
- Created the section Resources > Customization > Beagle for React Native > Cache.
- Created the section Resources > Customization > Beagle for React Native > WebView.
- Created the section Resources > Customization > Beagle for React Native > Accessing the localhost.
- Created the section Resources > Customization > Beagle for React Native > Local images.
- Created the section Resources > Customization > Beagle for React Native > Development status.
- Translated everything to portuguese.
- Adjusted weights for every backend page so …
=> Documentation for Beagle React Native

.github/ISSUE_TEMPLATE/documentation_issue.md
Updates the issue template to a more friendly user interface.
=> chore: updates the documentation_issue.md

content/en/get-started/installing-beagle/backend.md, content/en/get-started/installing-beagle/react-native.md, content/en/get-started/using-beagle/backend.md, content/en/get-started/using-beagle/react-native.md, content/en/overview.md, content/en/resources/customization/beagle-for-backend/_index.md, content/en/resources/customization/beagle-for-backend/beagle-framework.md, content/en/resources/customization/beagle-for-backend/serialization.md, content/en/resources/customization/beagle-for-react-native/_index.md, content/en/resources/customization/beagle-for-react-native/cache.md, content/en/resources/customization/beagle-for-react-native/development.md, content/en/resources/customization/beagle-for-react-native/local-images.md, content/en/resources/customization/beagle-for-react-native/localhost.md, content/en/resources/customization/beagle-for-react-native/web-view.md, content/pt/get-started/installing-beagle/backend.md, content/pt/get-started/installing-beagle/react-native.md, content/pt/get-started/using-beagle/backend.md, content/pt/get-started/using-beagle/react-native.md, content/pt/overview.md, content/pt/resources/customization/beagle-for-backend/_index.md, content/pt/resources/customization/beagle-for-backend/beagle-framework.md, content/pt/resources/customization/beagle-for-backend/serialization.md, content/pt/resources/customization/beagle-for-react-native/_index.md, content/pt/resources/customization/beagle-for-react-native/cache.md, content/pt/resources/customization/beagle-for-react-native/development.md, content/pt/resources/customization/beagle-for-react-native/local-images.md, content/pt/resources/customization/beagle-for-react-native/localhost.md, content/pt/resources/customization/beagle-for-react-native/web-view.md
Adds reactive native documentation into the docs release version 1.8
=> Feature/react native docs v1.8

content/pt/get-started/installing-beagle/react-native.md, content/pt/get-started/using-beagle/react-native.md
traduz a descrição que estava em inglês para português.
=> fix:reactive-native-docs-main

content/en/plugins/beagle-xcode-templates.md
=> fix: changing http to https

content/en/release-notes.html, content/pt/release-notes.html
=> feat: Fix image assets for release-notes.html

content/en/api/components/ui/textinput.md, content/pt/api/components/ui/textinput.md
Updates the text input info, attribute details and table structure
=> refactor: updates the text input info, attribute details and table structure v1.8

content/en/api/components/ui/textinput.md, content/pt/api/components/ui/textinput.md
updates the text input info, attribute details and table structure
=> refactor: updates the text input info, attribute details and table structure v1.7

content/en/ios/beagle-helpers/_index.md, content/en/ios/beagle-helpers/beagle-defaults.md, content/en/ios/beagle-helpers/beagle-scaffold.md, content/en/ios/beagle-helpers/overview.md, content/pt/ios/beagle-helpers/_index.md, content/pt/ios/beagle-helpers/beagle-defaults.md, content/pt/ios/beagle-helpers/beagle-scaffold.md, content/pt/ios/beagle-helpers/overview.md
Beagle-helpers refactored on iOS.
=> refactoring beagle-helpers

config/_default/config.toml, layouts/shortcodes/playground.html
Fixed playground in docs-beta.
=> Fix playground in docs-beta

content/en/resources/beagle-kapt-android.md, content/pt/resources/beagle-kapt-android.md
Signed-off-by: Paulo Cesar Meurer <paulo.meurer@zup.com.br>
=> feat: add Android kapt doc

.github/workflows/S3-upload.yml
Change the enviroment variables to use aws secret manager
=> feat: Update worfklow for uploading the doc

content/en/android/getting-started.md, content/pt/android/getting-started.md
=> feat: Adds show screen section for android

content/en/android/getting-started.md, content/en/android/libs/beagle-grpc-android.md, content/pt/android/getting-started.md, content/pt/android/libs/beagle-defaults.md, content/pt/android/libs/beagle-grpc-android.md
Signed-off-by: uziasferreirazup <uzias.ferreira@zup.com.br>
With new version of AGP the core of Beagle was migrate to JAVA 11 and because this I updated the doc with new min Version
=> chore: update min version of java in android project

content/en/_index.md, content/en/release-notes.html, content/pt/_index.md, content/pt/release-notes.html
Updates some release notes icons and the index files for the main page.
=> Release notes update

content/en/android/overview.md
I believe the word scratch was misspelled.
=> Fix a typo

content/en/web/react/using-beagle.md, content/pt/web/react/using-beagle.md
Updates docs descriptions for Web React
=> Updates Web Docs

content/en/resources/context-dsl.md, content/en/resources/dsl-operations/arrays-manipulation-operator.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- 'Added Resources > Context DSL - English Version'
=> Added Context DSL - English Version

CONTRIBUTING.md, README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- Updated README and CONTRIBUTING.
=> Updated readme and contributing

content/en/android/customization/action/simple-action.md, content/pt/android/customization/action/simple-action.md
=> feat: adjusts custom action example for android

content/en/backend/customization/_index.md, content/en/backend/get-started/_index.md, content/en/backend/overview.md, content/en/backend/support-libraries/_index.md, content/pt/backend/customization/_index.md, content/pt/backend/get-started/_index.md, content/pt/backend/overview.md
- Added overview page for backend documentation.
- Tweaks some missing descriptions.
=> Adds overview pages and tweaks descriptions

.github/workflows/horusec.yml, horusec-config.json
=> Updates horusec action

.github/workflows/horusec.yml, config/_default/config.toml, config/development/config.toml, horusec-config.json
=> inclusion of GTM code

content/en/_index.md, content/pt/_index.md
adjust link to go to correct repository
=> docs: update link to repository flutter

.github/workflows/horusec.yml
- Removes unused env from action
=> updates horusec url

config/_default/config.toml, config/development/config.toml
- Added missing gtm key
Signed-off-by: Hector <hector.custodio@zup.com.br>
=> Adds missing gtm keys

content/en/android/getting-started.md, content/pt/android/getting-started.md
- Android getting started had some missing details that could lead to extra time on configuring it for the first time. I then added a little bit more of detailing on some specific points of the installing and getting started with the library.
- Image sizes
- Descriptions
=> feat: Improves Android getting started Main

content/en/api/components/layout/gridview.md, content/pt/api/components/layout/gridview.md
Signed-off-by: Tiago Peres França <tiago.franca@zup.com.br>
Documentation change for this PR in the backend: https://github.com/ZupIT/beagle-backend-kotlin/pull/65
=> feat: GridView.itemAspectRatio

content/en/api/components/ui/image/imagepath.md, content/pt/api/components/ui/image/imagepath.md
Signed-off-by: Tiago Peres França <tiago.franca@zup.com.br>
Adds binding to the type of ImagePath.mobileId and imagePath.url.
=> fix: imagepath docs

.github/workflows/S3-upload.yml
=> Updates prod publish

.github/workflows/horusec.yml, content/en/ios/customization/custom-widget/custom-widget.md, horusec-config.json
- Update English version of ios/customization/custom-widget/custom-widget.md according to its Portuguese version.
- Resolve task for content/en/ios/customization/custom-widget/custom-widget.md file on issue #836 
- fix horusec parameter to the horusec-config.json
=>  Update English version of custom-widget.md file

content/en/web/angular/using-beagle.md, content/en/web/commons/advanced-topics/rendering.md, content/en/web/commons/advanced-topics/the-beagle-view.md
- Updates english web files documentation for Beagle version 2.0
=> Fix/updates web docs 2.0

content/en/resources/components-positioning/basis.md, content/en/resources/components-positioning/grow.md, content/en/resources/components-positioning/overview.md, content/en/resources/components-positioning/padding.md, content/en/resources/components/composed-component.md, content/en/resources/dsl-operations/arrays-manipulation-operator.md, content/en/resources/dsl-operations/comparison-operator.md, content/en/resources/dsl-operations/logic-operator.md, content/en/resources/dsl-operations/other-operators.md, content/en/resources/dsl-operations/string-manipulation-operator.md
- Updates resource files for Beagle's 2.0 features
=> Fix/update resource docs 2.0

content/en/api/operations/string-manipulation-operator.md
- Update English version of string-manipulation-operator.md according to
its Portuguese version
=> Update string-manipulation-operator.md English ver

.gitignore, README.md, package-lock.json
- Add package-lock.json as best practice
- Remove package-lock.json from .gitignore
- Update README according to npm package manegment
=> Add package-lock.json

content/en/api/operations/other-operators.md
- Update English version of other-operators.md according to its
Portuguese version
=> Update other-operators.md English version

.github/workflows/S3-upload.yml
- Changes upload method to S3 AWS
=> Changes upload mode

content/en/api/operations/arrays-manipulation-operator.md
- Update English version of arrays-manipulation-operator.md according to
its Portuguese version
=> fiz/836 Update arrays-manipulation-operator.md English ver

content/en/api/operations/logic-operator.md
- Update English version of logic-operator.md according to its
Portuguese version
=> fix/836 Update logic-operator.md English version

content/en/api/operations/arrays-manipulation-operator.md, content/en/api/operations/overview.md, content/pt/api/operations/arrays-manipulation-operator.md
=> feat: Operation array revised and translated to EN

content/pt/flutter/navigation/_index.md, content/pt/flutter/navigation/navigation-controllers.md, content/pt/flutter/navigation/open-beagle-screen.md
- Adds Portuguese translation for navigation folder of Flutter 2.0 documentation
=> Flutter - Adds Portuguese translation for navigation folder

content/pt/flutter/getting-started.md
=> Fixes typo

content/pt/android/customization/serializer-deserializer.md
BeagleJsonSerializationFactory for custom types
=> [pt_BR]BeagleJsonSerializationFactory for custom types

content/en/android/customization/serializer-deserializer.md
BeagleJsonSerializationFactory for custom types
=> [en_US]BeagleJsonSerializationFactory for custom types

content/en/api/components/layout/screen/overview.md, content/pt/api/components/layout/screen/overview.md
=> feat: updates the screen component table details.

content/en/ios/customization/custom-widget/custom-widget.md, content/pt/ios/customization/custom-widget/custom-widget.md
BeagleRenderer now adds automatically AutoLayoutWrapper for a component built with AutoLayout.
https://github.com/stack-spot/beagle-ios/pull/7
=> feat: iOS - BeagleRenderer now adds automatically AutoLayoutWrapper

content/en/release-notes.html
=> fix: adjusts release notes

.github/workflows/prepare-release.yml
Removes acl upload as the bucket configurations does not accept it.
=> Removes acl option

.github/workflows/prepare-release.yml
Updates release and fixes merge.
=> Removes acl option (#882)

config/_default/config.toml
Reverts config version variable
=> Fixes config var

content/en/android/customization/deep-link-handler.md, content/pt/android/customization/deep-link-handler.md
=> feat: updates the DeepLink Android example

content/en/android/customization/deep-link-handler.md, content/pt/android/customization/deep-link-handler.md
=> feat: updates the DeepLink Android example - 1.10

content/en/api/components/layout/screen/navigation-bar.md, content/en/api/components/layout/screen/overview.md, content/pt/api/components/layout/screen/navigation-bar.md, content/pt/api/components/layout/screen/overview.md
fixes docs for screen.navigationBar.navigationItem.image
=> fix: screen component

content/en/android/tutorials/multiple-config-instances.md, content/pt/android/tutorials/multiple-config-instances.md
=> Update doc for beagle multiple config

content/en/api/operations/arithmetic-operator.md, content/en/api/operations/comparison-operator.md, content/en/api/operations/conversion-operators.md, content/pt/api/operations/arithmetic-operator.md, content/pt/api/operations/comparison-operator.md, content/pt/api/operations/conversion-operators.md
Signed-off-by: Daniel Tes Carrasque <daniel@zup.com.br>
Add the documentation related to [#47](https://github.com/ZupIT/beagle-ios/pull/47)
=> feat: Type coercion on some operations

content/en/android/customization/multiple-configurations.md, content/en/release-notes.html, content/pt/android/customization/multiple-configurations.md, content/pt/release-notes.html
=> release: 2.1

.github/workflows/S3-upload.yml, .github/workflows/beta-upload.yml
=> feat: Fixes aws tokens
